### ISSUE TITLE
I can't download pretrained model from OneDrive

### ISSUE THREAD

**Issue by heury** [Microsoft/human-pose-estimation.pytorch#1]
I got following error when I try to download pretrained model from OneDrive

Something went wrong
Please try again or refresh the page

**Comment by leoxiaobin** [comment]
could you tell me which your url you are using? It works for me.

**Comment by junluan** [comment]
@leoxiaobin person detection result of COCO val2017, this url: https://1drv.ms/f/s!AhIXJn_J-blWzzA1A-y1AH-pZQdS also fails

**Comment by mkocabas** [comment]
You can access it via: https://onedrive.live.com/?authkey=%21AKqtqKs162Z5W7g&id=56B9F9C97F261712%2110694&cid=56B9F9C97F261712

**Comment by leoxiaobin** [comment]
I have update the url, please try it again.

**Comment by jin-s13** [comment]
These url links (for pretrained model) still do not work for me. 

https://1drv.ms/f/s!AhIXJn_J-blW0D5ZE4ArK9wk_fvw

https://onedrive.live.com/redir?resid=56B9F9C97F261712!10302&authkey=!AFkTgCsr3CT9-_A&ithint=folder%2c

**Comment by leoxiaobin** [comment]
I have google drive's urls for pretrained models and annotations, please try it again.

**Comment by heury** [comment]
I can download pretrained models and annotations. Thanks
