### ISSUE TITLE
No module named 'nms.cpu_nms'

### ISSUE THREAD

**Issue by ArchNew** [Microsoft/human-pose-estimation.pytorch#10]
When I followed the instructions on readme, running "python pose_estimation/valid.py --cfg experiments/mpii/resnet50/256x256_d256x3_adam_lr1e-3.yaml --flip-test --model-file models/pytorch/pose_mpii/pose_resnet_50_256x256.pth.tar", it reported an error: 
ImportError: No module named 'nms.cpu_nms'

I've noticed there are cpu_nmn.pyx under 'human-pose-estimation.pytorch/lib/nms'. I ran the 'setup.py' under the same directory by typing 'python setup.py install'. Unfortunately, it didn't solve my problem. I also tried to add various path including cpu_nms.py,cpu_nms.so...in to the environment, no use.

**Comment by leoxiaobin** [comment]
I have updated the install instructions.
Please build the libs first.
```
cd ${POSE_ROOT}/lib
make
``

**Comment by ArchNew** [comment]
Thanks, problem solved.
One caveat, since we don't have python3 as default, we use a virtualenv with python3 as default to run this project. If some persons want to run it directly with python2 as the default, they may need to change the 'python' command in makefile into 'python3'.
