### ISSUE TITLE
Intuition of the `target_weight` in the loss

### ISSUE THREAD

**Issue by anuar12** [microsoft/human-pose-estimation.pytorch#100]
Hello, thank you for the great code!

I like the simplicity of the loss, however I don't understand one specific case when:
- the joint is not visible in the object patch AND there is a wrong prediction (FP), then the loss will be zero because the `target_weight=0`. Shouldn't one want to penalize such a case of FPs?

Why wouldn't you not use target_weight, then both FPs and FNs would be penalized which is good.

**Comment by zhuzhu18** [comment]
good idea!   Have you tried it? :+1:

**Comment by anuar12** [comment]
Yes, improved on my own dataset. If you make sure that patches don't include other objects, it noteceably improved my results. The reason it works better in their case because at least in case of MPII, the patches are given and they include several humans...

**Comment by mobeixiaoxin** [comment]
@anuar12  To be honest, your english level is so high that I can't understand what you write. You're great
