### ISSUE TITLE
0-based or 1-based indexing

### ISSUE THREAD

**Issue by koelscha** [microsoft/human-pose-estimation.pytorch#110]
I was just wondering if the joint coordinates are 0-based or 1-based. I know this will probably not have a huge impact on the performance, but I would like to get this right.

So, in https://tensorlayer.readthedocs.io/en/stable/_modules/tensorlayer/files/dataset_loaders/mpii_dataset.html there is no subtraction to align the joints. Also, the `id`s are 0-based. Did you confirm from the authors that the indices are 1-based or are you just assuming so?

**Comment by leoxiaobin** [comment]
For MPII dataset ids are 1-based, and for COCO dataset  ids are 0-based. We have confirmed with the authors of respectively dataset. 

Our code also has respectively processed that.
