### ISSUE TITLE
Can I run pose estimation part on posetrack datasets?

### ISSUE THREAD

**Issue by ArchNew** [Microsoft/human-pose-estimation.pytorch#12]
I noticed in the source code, your project support posetrack datasets. I plan to write a yaml file to run it on posetrack datasets. But I'm stumped on annotations' format. Do you support the original posetrack annotations (in matlab format)? or json verson of such annotations? or I have to turn it into coco format?

I'm sorry that I'm not very familiar with python, so I can't have those answers just by reading the source code.

Many thanks for any help you can offer.

**Comment by leoxiaobin** [comment]
The repo has not supported posetrack dataset now, if you want to use posetrack dataset, you need write a posetrack class to handle it.

**Comment by ArchNew** [comment]
Thanks!
