### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by lxtGH** [microsoft/human-pose-estimation.pytorch#125]
I use pretrained model to test with bbox but I got this error.

index created!
=> classes: ['__background__', 'person']
=> num_images: 5000
=> Total boxes: 378148
=> Total boxes after fliter low score@0.0: 378148
=> load 378148 samples
=> fail to read data/coco/images/val2017/000000466947.jpg
=> fail to read data/coco/images/val2017/000000491543.jpg
=> fail to read data/coco/images/val2017/000000106516.jpg
=> fail to read data/coco/images/val2017/000000565319.jpg
=> fail to read data/coco/images/val2017/000000098438.jpg
=> fail to read data/coco/images/val2017/000000251235.jpg
=> fail to read data/coco/images/val2017/000000295029.jpg
Traceback (most recent call last):
=> fail to read data/coco/images/val2017/000000221348.jpg
  File "pose_estimation/valid.py", line 172, in <module>
=> fail to read data/coco/images/val2017/000000327859.jpg
    main()
  File "pose_estimation/valid.py", line 168, in main
    final_output_dir, tb_log_dir)
  File "/home/lxt/project/human-pose-estimation.pytorch/pose_estimation/../lib/core/function.py", line 108, in validate
    for i, (input, target, target_weight, meta) in enumerate(val_loader):
  File "/home/lxt/torch1.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/lxt/torch1.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/lxt/torch1.0/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lxt/torch1.0/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lxt/torch1.0/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lxt/torch1.0/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lxt/project/human-pose-estimation.pytorch/pose_estimation/../lib/dataset/JointsDataset.py", line 84, in __getitem__
    raise ValueError('Fail to read {}'.format(image_file))
ValueError: Fail to read data/coco/images/val2017/000000466947.j

**Comment by lxtGH** [comment]
where is the image 000000251235.jpg on COCO val dataset

**Comment by lxtGH** [comment]
I

**Comment by trevor-taeyeop** [comment]
Hi, @lxtGH. 
I got similar errors. Could you share how to solve this issue?? 


> (hrsimple) user@user:/sdata1/workspace/simple-pose$ python pose_estimation/valid.py     --cfg experiments/coco/resnet50/256x192_d256x3_adam_lr1e-3.yaml     --flip-test     --model-file models/pytorch/pose_coco/pose_resnet_50_256x192.pth.tar
> /sdata1/workspace/simple-pose/pose_estimation/../lib/core/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>   exp_config = edict(yaml.load(f))
> => creating output/coco/pose_resnet_50/256x192_d256x3_adam_lr1e-3
> => creating log/coco/pose_resnet_50/256x192_d256x3_adam_lr1e-3_2020-05-25-14-25
> Namespace(cfg='experiments/coco/resnet50/256x192_d256x3_adam_lr1e-3.yaml', coco_bbox_file=None, flip_test=True, frequent=100, gpus=None, model_file='models/pytorch/pose_coco/pose_resnet_50_256x192.pth.tar', post_process=False, shift_heatmap=False, use_detect_bbox=False, workers=None)
> {'CUDNN': {'BENCHMARK': True, 'DETERMINISTIC': False, 'ENABLED': True},
>  'DATASET': {'DATASET': 'coco',
>              'DATA_FORMAT': 'jpg',
>              'FLIP': True,
>              'HYBRID_JOINTS_TYPE': '',
>              'ROOT': '/sdata1/dataset/coco_human/',
>              'ROT_FACTOR': 40,
>              'SCALE_FACTOR': 0.3,
>              'SELECT_DATA': False,
>              'TEST_SET': 'val2017',
>              'TRAIN_SET': 'train2017'},
>  'DATA_DIR': '',
>  'DEBUG': {'DEBUG': True,
>            'SAVE_BATCH_IMAGES_GT': True,
>            'SAVE_BATCH_IMAGES_PRED': True,
>            'SAVE_HEATMAPS_GT': True,
>            'SAVE_HEATMAPS_PRED': True},
>  'GPUS': '0',
>  'LOG_DIR': 'log',
>  'LOSS': {'USE_TARGET_WEIGHT': True},
>  'MODEL': {'EXTRA': {'DECONV_WITH_BIAS': False,
>                      'FINAL_CONV_KERNEL': 1,
>                      'HEATMAP_SIZE': array([48, 64]),
>                      'NUM_DECONV_FILTERS': [256, 256, 256],
>                      'NUM_DECONV_KERNELS': [4, 4, 4],
>                      'NUM_DECONV_LAYERS': 3,
>                      'NUM_LAYERS': 50,
>                      'SIGMA': 2,
>                      'TARGET_TYPE': 'gaussian'},
>            'IMAGE_SIZE': array([192, 256]),
>            'INIT_WEIGHTS': True,
>            'NAME': 'pose_resnet',
>            'NUM_JOINTS': 17,
>            'PRETRAINED': 'models/pytorch/imagenet/resnet50-19c8e357.pth',
>            'STYLE': 'pytorch'},
>  'OUTPUT_DIR': 'output',
>  'PRINT_FREQ': 100,
>  'TEST': {'BATCH_SIZE': 32,
>           'BBOX_THRE': 1.0,
>           'COCO_BBOX_FILE': 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json',
>           'FLIP_TEST': True,
>           'IMAGE_THRE': 0.0,
>           'IN_VIS_THRE': 0.2,
>           'MODEL_FILE': 'models/pytorch/pose_coco/pose_resnet_50_256x192.pth.tar',
>           'NMS_THRE': 1.0,
>           'OKS_THRE': 0.9,
>           'POST_PROCESS': True,
>           'SHIFT_HEATMAP': True,
>           'USE_GT_BBOX': True},
>  'TRAIN': {'BATCH_SIZE': 32,
>            'BEGIN_EPOCH': 0,
>            'CHECKPOINT': '',
>            'END_EPOCH': 140,
>            'GAMMA1': 0.99,
>            'GAMMA2': 0.0,
>            'LR': 0.001,
>            'LR_FACTOR': 0.1,
>            'LR_STEP': [90, 120],
>            'MOMENTUM': 0.9,
>            'NESTEROV': False,
>            'OPTIMIZER': 'adam',
>            'RESUME': False,
>            'SHUFFLE': True,
>            'WD': 0.0001},
>  'WORKERS': 4}
> => loading model from models/pytorch/pose_coco/pose_resnet_50_256x192.pth.tar
> /home/user/anaconda3/envs/hrsimple/lib/python3.7/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
>   warnings.warn(warning.format(ret))
> loading annotations into memory...
> Done (t=0.28s)
> creating index...
> index created!
> => classes: ['__background__', 'person']
> => num_images: 5000
> => load 6352 samples
> 188
> => fail to read /sdata1/dataset/coco_human/images/val2017/000000580294.jpg
> Test: [0/199]	Time 1.540 (1.540)	Loss 0.0003 (0.0003)	Accuracy 0.905 (0.905)
> Traceback (most recent call last):
>   File "pose_estimation/valid.py", line 167, in <module>
>     main()
>   File "pose_estimation/valid.py", line 163, in main
>     validate(config, valid_loader, valid_dataset, model, criterion, final_output_dir, tb_log_dir)
>   File "/sdata1/workspace/simple-pose/pose_estimation/../lib/core/function.py", line 110, in validate
>     for i, (input, target, target_weight, meta) in enumerate(val_loader):
>   File "/home/user/anaconda3/envs/hrsimple/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
>     return self._process_next_batch(batch)
>   File "/home/user/anaconda3/envs/hrsimple/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
>     raise batch.exc_type(batch.exc_msg)
> ValueError: Traceback (most recent call last):
>   File "/home/user/anaconda3/envs/hrsimple/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/home/user/anaconda3/envs/hrsimple/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/sdata1/workspace/simple-pose/pose_estimation/../lib/dataset/JointsDataset.py", line 81, in __getitem__
>     raise ValueError('Fail to read {}'.format(image_file))
> ValueError: Fail to read /sdata1/dataset/coco_human/images/val2017/000000580294.jpg
