### ISSUE TITLE
ImportError: No module named core.config

### ISSUE THREAD

**Issue by ss32** [Microsoft/human-pose-estimation.pytorch#13]
Torch v0.5, requirements satisfied with `pip install -r requirements.txt` and trying to run `valid.py` with the suggested model/config for Coco

```
python pose_estimation/valid.py --cfg experiments/mpii/resnet50/256x256_d256x3_adam_lr1e-3.yaml     --flip-test     --model-file models/pytorch/pose_coco/pose_resnet_50_256x256.pth.tar
Traceback (most recent call last):
  File "pose_estimation/valid.py", line 25, in <module>
    from core.config import config
ImportError: No module named core.config
```

I saw in the paper that this was based on the latest Mask R-CNN and a similar issue was raised [here](https://github.com/facebookresearch/Detectron/issues/475) so is the Facebook detectron required to run this code?

**Comment by leoxiaobin** [comment]
you can check your sys.path, usually it is because that your sys path has another module also named as core

**Comment by luohuan2uestc** [comment]
@ss32 you should use python3.

**Comment by ss32** [comment]
@luohuan2uestc that did it.  Solved.

**Comment by oneskey01** [comment]
Could you please tell me how to solve it.
