### ISSUE TITLE
cracked，cracked，cracked——蓝屏，蓝屏，训练几次蓝屏，怎么解决？！

### ISSUE THREAD

**Issue by LiutsingWo** [microsoft/human-pose-estimation.pytorch#130]
How to do it？

**Comment by WuZhuoran** [comment]
Can you please show more output before crash? 
Also it would be great to show your train/test environments.

**Comment by faedtodd** [comment]
你激动你马呢

**Comment by liuchanfeng165** [comment]
> 你激动你马呢

If u solve this ,you have power to  describe fully the sentence .
environment: win7 -64bit，pytorch1.10 , gtx1070.
——give you with gift-For God's sake shut up. I can't hear myself think!

**Comment by liuchanfeng165** [comment]
> Can you please show more output before crash?
> Also it would be great to show your train/test environments.

thanks。it is ok in linux but win7. Actually I dont care it now  .
