### ISSUE TITLE
import tensorboardX, Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by lxltaibo** [Microsoft/human-pose-estimation.pytorch#14]
When 'import tensorboardX', it reported an error: Segmentation fault (core dumped) . The same error occur when run the train.py. I tried tensorboardX1.2 and 1.4  by 'conda install'.
Environment:
pytorch: v0.4.0
python: v3.6 (anaconda3)
cuda: 8.0
cudnn: v6

**Comment by lxltaibo** [comment]
I solved the problem by re-install the python packages: google, protobuf and libprotbuf.

**Comment by gyc521zsc** [comment]
Did you solve this ?

**Comment by gyc521zsc** [comment]
which protobuf version?
