### ISSUE TITLE
Your results on COCO val2017 is based on OKS or PCKh?

### ISSUE THREAD

**Issue by ArchNew** [Microsoft/human-pose-estimation.pytorch#15]
I noticed that one of the requirements is installing cocoapi. So I'm courios your results on COCO val2017 is based on OKS[0.5~0.95] or PCKh？

**Comment by leoxiaobin** [comment]
it's based on OKS[0.5-0.95]

**Comment by Naman-ntc** [comment]
@leoxiaobin Hi, could point to how do you call the OKS metric while training. I can't seem to find how you perform evaluation for coco dataset. There was an evaluate function in `coco.py` but neither I could find any function call to that method nor I understood how to pass arguments to that method.

**Comment by Naman-ntc** [comment]
@ArchNew  did you figure it how is OKS being calculated?
