### ISSUE TITLE
Why don't you use Integral human pose regression?

### ISSUE THREAD

**Issue by ArchNew** [microsoft/human-pose-estimation.pytorch#153]
From what I can understand, the paper "Integral Human Pose Regression" is also your group's work. According to that paper, Integral regression has a better result than heatmaps. So, why don't you use it on this paper or HRNet?

**Comment by leoxiaobin** [comment]
This work and our another work of HRNet are mainly focused on proposing a simple architecture or backbone for human pose estimation. 
For other parts we want to keep the most common setting to compare with other methods.

**Comment by leoxiaobin** [comment]
This work and oHRNet is mainly focus on the proposing a simple architecture or backbone for human pose estimation. 
For other parts we want to keep the most common setting to compare with other methods.

**Comment by ArchNew** [comment]
Thanks!
