### ISSUE TITLE
how to use  model predict on my own datasett

### ISSUE THREAD

**Issue by yjfncu** [Microsoft/human-pose-estimation.pytorch#18]
hello,thank you for your perfect project, but I don't know how to use  your model to predict on my own dataset, I just use a file like predict.py which input only include model path and my dataset path to predict on my dataset.thank you

**Comment by leoxiaobin** [comment]
you can follow our validation code, and for you own dataset, you need write your own dataset class.

**Comment by yjfncu** [comment]
yes,I have done it,thank you

**Comment by WangZhaoxue** [comment]
> you can follow our validation code, and for you own dataset, you need write your own dataset class.

what do you mean by your own dataset class? Do i need to write a new code like coco.py?
