### ISSUE TITLE
During evaluation, the center and  scale is used?

### ISSUE THREAD

**Issue by Fangyh09** [Microsoft/human-pose-estimation.pytorch#19]
Hi, I see it uses center and  scale when fetching validation dataset.   Where are the center and scale come from?  They are predicted by human detector or the gt information?
https://github.com/Microsoft/human-pose-estimation.pytorch/blob/8fc31b4dad3dee31b5d69f8cb2e8b781f811ab23/lib/dataset/JointsDataset.py#L103

**Comment by leoxiaobin** [comment]
When training processing, we use the gt. When validation, you can use center or scale from prediction of person detector or gt information depending on what you want to do.
