### ISSUE TITLE
About the eval() function in train.py

### ISSUE THREAD

**Issue by ArchNew** [Microsoft/human-pose-estimation.pytorch#20]
in main() function of 'train.py', line 92~94
```python
    model = eval('models.'+config.MODEL.NAME+'.get_pose_net')(
        config, is_train=True
    )
```
I can't find the reference of the eval function and the functionality of the parenthesis after the eval().
In PyCharm, when I "ctrl-click" on the eval, it brings me to an eval definition that only has "pass" in it.

**Comment by fire717** [comment]
same question, how do u solve it? thx

**Comment by fire717** [comment]
got it, it's python's func
