### ISSUE TITLE
I trained on my own dataset, but I was unable to use model_best.path.tar to validate

### ISSUE THREAD

**Issue by ArchNew** [Microsoft/human-pose-estimation.pytorch#28]
I noticed that when I trained on my own dataset, your code produced three model: checkpoint.pth.tar, final_state.pth.tar, and model_best.path.tar. Unfortunately, I was unable to load the model_best.pth.tar in validation. It reports "Missing Key(s) Erro" in state_dict.

**Comment by leoxiaobin** [comment]
The best model is saved as the model using nn.DataParallel, which stores the model in module, and now you are trying to load it without DataParallel. You can either add a nn.DataParallel temporarily in your network for loading purposes, or you can load the weights file, create a new ordered dict without the module prefix, and load it back.

**Comment by ArchNew** [comment]
Thanks!

**Comment by ArchNew** [comment]
> The best model is saved as the model using nn.DataParallel, which stores the model in module, and now you are trying to load it without DataParallel. You can either add a nn.DataParallel temporarily in your network for loading purposes, or you can load the weights file, create a new ordered dict without the module prefix, and load it back.

So, your code doesn't have the functionality to load 'best model'?

**Comment by leoxiaobin** [comment]
No, there is not function for that. You can load the 'best model' like this:
```
checkpoint = torch.load(resume)
state_dict =checkpoint['state_dict']

from collections import OrderedDict
new_state_dict = OrderedDict()
for k, v in state_dict.items():
    name = k[7:] # remove 'module.' of dataparallel
    new_state_dict[name]=v

model.load_state_dict(new_state_dict)
```

**Comment by leoxiaobin** [comment]
You can also send a PR for that.

**Comment by ArchNew** [comment]
Thank you very much!
