### ISSUE TITLE
I'm curious, why don't you use ResNet in torchvision?

### ISSUE THREAD

**Issue by ArchNew** [Microsoft/human-pose-estimation.pytorch#29]
Is it because ResNet in torchvision is not up-to-date? Say, it may not have BN within the Residual Module?

**Comment by leoxiaobin** [comment]
The pre-trained backbone models are from torchvision.

**Comment by ArchNew** [comment]
But ... I see there's a version of your own here in the project's source code...you didn't use it?

**Comment by leoxiaobin** [comment]
I am not sure if the models from torchvison will change in the feature, so I also keep them by ourselves.

**Comment by ArchNew** [comment]
Thanks!
