### ISSUE TITLE
The result I get from valid.py is different from what I get from cocoapi.

### ISSUE THREAD

**Issue by ArchNew** [Microsoft/human-pose-estimation.pytorch#30]
I did the validation via valid.py and put the json file generated in the process through the cocoapi. These two gave rather different results. The cocoapi's result is more than 20% lower than valid.py's. Do you have different coordinates system? If so, could you so kindly tell us the conversion formula between your system and cocoapi's? Thanks!

**Comment by leoxiaobin** [comment]
the system's results are also from cocoapi

**Comment by ArchNew** [comment]
I know, that's why I'm confused. I use valid.py, the results is: (on my own datasets)
```shell
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.687
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.876
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.754
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.410
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.725
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.714
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.885
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.773
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.444
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.753
```
and I took out the json generated here, put it through cocoapi, the result is:
```shell
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.509
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.914
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.572
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.031
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.375
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.526
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.093
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.505
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.557
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.053
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.443
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.575
```

I took a peek at the result, addition to image_id, category_id, keypoints and score, the file also has 'center' and 'scale'. Should I use the 'center' and 'scale' to perform some kind of transformation in order to have the results valid.py gave out?

**Comment by ArchNew** [comment]
Thanks! I'm a rookie in research, still have got a lot of things to learn.

**Comment by junjieAI** [comment]
I've found the bug~

**Comment by zhongxiaofang-run** [comment]
I also have meet this problem.Do you  solved this problem? Please help me. thank you

Accumulating evaluation results...
DONE (t=0.04s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.000
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.000

**Comment by ArchNew** [comment]
I suspect your understanding of the coco keypoints evaluation standards OKS is not sufficient. The "area" of the segmentation plays a key role in the evaluation. If you set the "area" to 0, the results would be wrong. For simple baselines, there's no segmentation in posetrack dataset, their solution is to use bounding box area in place of segmentation area. If you do evaluation by cocoapi, it's highly unrecommanded.

**Comment by simonJJJ** [comment]
> I've found the bug~

Hi, what's the bug?

**Comment by jfpalngipang** [comment]
> I've found the bug~

@cs-heibao, I have been trying to make this work but to no avail. May I know what you fixed? It would really help.
