### ISSUE TITLE
Which posetrack standard do you use during evaluation?

### ISSUE THREAD

**Issue by ArchNew** [Microsoft/human-pose-estimation.pytorch#37]
There are two papers regarding posetrack. In paper "PoseTrack: Joint Multi-Person Pose Estimation and Tracking", the PCKh is 20% of head bounding box's diagonal. In paper "PoseTrack: A Benchmark for Human Pose Estimation and Tracking", the PCKh is 30% of head bounding box's diagonal. I'm wondering, which one you guys used? In PoseTrack GitHub site, their evaluation toolkit "poseval" uses 30% version.

**Comment by wjbKimberly** [comment]
The default value is 0.5. You can check "lib/core/evaluate.py" for details.
