### ISSUE TITLE
can't replicate your performance at 72.4 testing with gt_box

### ISSUE THREAD

**Issue by FiredFree** [Microsoft/human-pose-estimation.pytorch#39]
thanks for your release code. 
I run you code for 140 epochs ,  just reach 71.6 map.
does this have something with random seed in dataset ?

**Comment by FiredFree** [comment]
I'm sorry. I have made a mistake.

**Comment by Gary-Shi** [comment]
@FiredFree Hi！I've encountered the same problem as yours... Could u plz tell me how u solved it?
