### ISSUE TITLE
some questions about select_data

### ISSUE THREAD

**Issue by djangogo** [Microsoft/human-pose-estimation.pytorch#46]
Hi @leoxiaobin 
Thanks for sharing your excellent work!
I am curious about following line in the select_data function in you code.
[metric](https://github.com/Microsoft/human-pose-estimation.pytorch/blob/master/lib/dataset/JointsDataset.py#L161)
```python
metric = (0.2 / 16) * num_vis + 0.45 - 0.2 / 16
```
num_vis is the number of labelled joints.

Would you please explain how to calculate the metric?
Is 16 the number of symmetric joints in coco dataset?
Do you use the select_data only in COCO dataset？
What is 0.45 ?
Why minus 0.2 / 16?
Why select those data which are greater than the metric?
```python
if ks > metric:
                db_selected.append(rec)
```
[greater than the metric](https://github.com/Microsoft/human-pose-estimation.pytorch/blob/master/lib/dataset/JointsDataset.py#L162-L163)

**Comment by leoxiaobin** [comment]
The code is for experiments of 14/20 http://presentations.cocodataset.org/COCO17-Keypoints-TeamOKS.pdf, but we did not use in our simple baseline.

**Comment by djangogo** [comment]
Thank you!
