### ISSUE TITLE
Could u provide the COCO_test2017_detections_person.json ?

### ISSUE THREAD

**Issue by ZhuohaoMai** [Microsoft/human-pose-estimation.pytorch#49]
hi, I have trained my own model, could you provide detections_person.json you used, so that i can compare to the COCO leaderboard. thank u .

**Comment by leoxiaobin** [comment]
Please download from [OneDrive](https://1drv.ms/f/s!AhIXJn_J-blWzzDXoz5BeFl8sWM-) or [GoogleDrive](https://drive.google.com/drive/folders/1fRUDNUDxe9fjqcRZ2bnF_TKMlO0nB_dk?usp=sharing).
