### ISSUE TITLE
Why "imagenet pretrained model dose not exist" even if I put models in "models/pytorch/imagenet"

### ISSUE THREAD

**Issue by RobinWenqian** [Microsoft/human-pose-estimation.pytorch#53]
![image](https://user-images.githubusercontent.com/18494091/48389277-b45cd380-e737-11e8-99c9-7552aee63ec8.png)
![image](https://user-images.githubusercontent.com/18494091/48389293-c6d70d00-e737-11e8-950c-3a6fb95097ce.png)
As shown in the picture

**Comment by leoxiaobin** [comment]
running dir should be ${POSE_ROOT}, not ${POSE_ROOT}/pose_estimation

**Comment by RobinWenqian** [comment]
thank you ! And how can I use trained models for my own pictures?

**Comment by leoxiaobin** [comment]
You can look into our valid.py
