### ISSUE TITLE
Is the deepcopy necessary?

### ISSUE THREAD

**Issue by absurdliyang** [Microsoft/human-pose-estimation.pytorch#54]
https://github.com/Microsoft/human-pose-estimation.pytorch/blob/a515cd38d33fad926501980c27ecafc4eeff9937/lib/dataset/JointsDataset.py#L64

Is the copy.deepcopy() necessary here? Can we directly adopt the value of the index position?

**Comment by leoxiaobin** [comment]
You need use deepcopy, because in the data augmentation part, it will directly change the value of db_rec.
