### ISSUE TITLE
There is some explanation mistake in README

### ISSUE THREAD

**Issue by SixHeo** [Microsoft/human-pose-estimation.pytorch#59]
**Valid on COCO val2017 using pretrained models**

python pose_estimation/valid.py \
    --cfg experiments/mpii/resnet50/256x256_d256x3_adam_lr1e-3.yaml \
    --flip-test \
    --model-file models/pytorch/pose_coco/pose_resnet_50_256x256.pth.tar

I think the first and third line, 256x256 has to be changed to 256x192.\
Or both directory must be changed to mpii

**Comment by leoxiaobin** [comment]
fixed.
