### ISSUE TITLE
Pre-trained models are not valid .tar files

### ISSUE THREAD

**Issue by lutzroeder** [Microsoft/human-pose-estimation.pytorch#70]
The pre-trained models have a `.pth.tar` extension but are not valid `.tar` files. The content is in Pickle format and extension should be `.pth`.

**Comment by leoxiaobin** [comment]
Yes, I will change the extension when I have time.

**Comment by DepressedSage** [comment]
The issue is still there.
I downloaded the files from both Google Drive and One Drive. 
Models downloaded from both the places result in being not valid tar files.
