### ISSUE TITLE
Why do you disable cudnn for batch_norm?

### ISSUE THREAD

**Issue by jin-s13** [Microsoft/human-pose-estimation.pytorch#8]
Thank you for releasing the code. The README reads that it is required to disable cudnn for batch_norm. Would you please explain why we should do this?

**Comment by 7color94** [comment]
Hi, I wonder under what circumstances will this kind of cudnn bn bug appear ? Does the cudnn bn bug appear for all tasks, not only human pose estimation ?

**Comment by leoxiaobin** [comment]
I am not sure if any other task has also this problem and also not know what's the root cause for this.

**Comment by makslevental** [comment]
@leoxiaobin you don't need a `sed`. you can monkey patch

```python
def monkey_patch_bn():
    # print(inspect.getsource(torch.nn.functional.batch_norm))
    def batch_norm(input, running_mean, running_var, weight=None, bias=None,
                   training=False, momentum=0.1, eps=1e-5):
        if training:
            size = input.size()
            size_prods = size[0]
            for i in range(len(size) - 2):
                size_prods *= size[i + 2]
            if size_prods == 1:
                raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))

        return torch.batch_norm(
            input, weight, bias, running_mean, running_var,
            training, momentum, eps, False
        )
    torch.nn.functional.batch_norm = batch_norm
```

**Comment by LordLiang** [comment]
> @leoxiaobin you don't need a `sed`. you can monkey patch
> 
> ```python
> def monkey_patch_bn():
>     # print(inspect.getsource(torch.nn.functional.batch_norm))
>     def batch_norm(input, running_mean, running_var, weight=None, bias=None,
>                    training=False, momentum=0.1, eps=1e-5):
>         if training:
>             size = input.size()
>             size_prods = size[0]
>             for i in range(len(size) - 2):
>                 size_prods *= size[i + 2]
>             if size_prods == 1:
>                 raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
> 
>         return torch.batch_norm(
>             input, weight, bias, running_mean, running_var,
>             training, momentum, eps, False
>         )
>     torch.nn.functional.batch_norm = batch_norm
> ```

Hi, I want to know where I should add monkey_patch_bn? main.py? call it before training?

**Comment by makslevental** [comment]
@LordLiang i would call it right after importing `torch.nn`

**Comment by mgarbade** [comment]
is this still relevant in higher versions of pytorch? (eg version 1.4)

**Comment by soulslicer** [comment]
> > @leoxiaobin you don't need a `sed`. you can monkey patch
> > ```python
> > def monkey_patch_bn():
> >     # print(inspect.getsource(torch.nn.functional.batch_norm))
> >     def batch_norm(input, running_mean, running_var, weight=None, bias=None,
> >                    training=False, momentum=0.1, eps=1e-5):
> >         if training:
> >             size = input.size()
> >             size_prods = size[0]
> >             for i in range(len(size) - 2):
> >                 size_prods *= size[i + 2]
> >             if size_prods == 1:
> >                 raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
> > 
> >         return torch.batch_norm(
> >             input, weight, bias, running_mean, running_var,
> >             training, momentum, eps, False
> >         )
> >     torch.nn.functional.batch_norm = batch_norm
> > ```
> 
> Hi, I want to know where I should add monkey_patch_bn? main.py? call it before training?

How do I do this, if I am using nn.Sequential?

```
def convbn(in_planes, out_planes, kernel_size, stride, pad, dilation, bn_running_avg=False):
    return nn.Sequential(nn.Conv2d(in_planes, out_planes,
                                   kernel_size=kernel_size, stride=stride,
                                   padding=dilation if dilation > 1 else pad,
                                   dilation=dilation, bias=False),
                         nn.BatchNorm2d(out_planes,
                                        track_running_stats=bn_running_avg))
```
