### ISSUE TITLE
Training suspends after validation

### ISSUE THREAD

**Issue by crsailing** [Microsoft/human-pose-estimation.pytorch#9]
Hi, I met a question when training.
During training stage,  after evaluating the current results, training suspended. Log info as below:
 
Accumulating evaluation results...
DONE (t=0.06s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.339
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.665
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.300
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.329
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.360
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.391
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.693
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.377
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.370
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.420
=> coco eval results saved to output/coco/pose_resnet_50/256x192_d256x3_adam_lr1e-3/results/keypoints_val2017_results.pkl
Traceback (most recent call last):
  File "pose_estimation/train.py", line 206, in <module>
    main()
  File "pose_estimation/train.py", line 180, in main
    writer_dict)
  File "/media/human-pose-estimation.pytorch/pose_estimation/../lib/core/function.py", line 182, in validate
    filenames, imgnums)
  File "/media/human-pose-estimation.pytorch/pose_estimation/../lib/dataset/coco.py", line 329, in evaluate
    name_value = OrderedDict(info_str)
TypeError: 'NoneType' object is not iterable

**Comment by leoxiaobin** [comment]
Please try the latest code 55827b210ee892e570dd43302984b0dd2d46c64e, I have fixed the bug.
